site_name: Конструктор домашней автоматизации и умной квартиры
theme: readthedocs
docs_dir: docs
pages:
- 'Сообщество': 'index.md'
- Сценарии:
  - 'Влажность почвы': 'Влажность почвы.md'
  - 'Автополив цветов': 'Автополив цветов.md'
  - 'Умная розетка': 'Умная розетка.md'
  - 'Радиореле': 'Радиореле.md'
  - 'Управление освещением': 'Управление освещением.md'
  - 'Подсветка': 'Умная подсветка.md'
  - 'Метеостанция': 'Метеостанция.md'
  - 'Увлажнитель воздуха': 'Увлажнитель воздуха.md'
  - 'Радионяня': 'Радионяня.md'
  - 'Датчик окна': 'Датчик окна.md'
  - 'Датчик движения (Радио)': 'Датчик движения.md'
  - 'Детектор движения (ИК)': 'Детектор движения.md'
  - 'Люксметер': 'Люксметер.md'
  - 'Домашний огород': 'Домашний огород.md'
  - 'Видеонаблюдение': 'Видеонаблюдение.md'
- Развертывание:
  - 'Выбор контроллера': 'Реализация.md'
  - 'Установка': 'Установка.md'
  - 'Настройка': 'Настройка.md'
  - 'Доступ из Интернет': 'Работа через Интернет.md'
  - 'Резервирование': 'Резервирование.md'
  - 'Мобильное приложение': 'Мобильное приложение.md'
- Прототипирование:
  - 'Элементная база': 'Элементная база.md'
  - 'Микроконтроллеры': 'Микроконтроллеры.md'
  - 'Алгоритм выбора': 'Выбор элементов.md'
- Концепция:
  - 'Умный дом': 'Введение.md'
  - 'Обзор рынка': 'Обзор рынка.md'
  - 'Архитектура': 'Архитектура.md'
  - 'Инфраструктура': 'Инфраструктура.md'
